# Generated by Django 3.1.4 on 2022-10-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=255, unique=True)),
                ('Image', models.ImageField(blank=True, default='category/notfound.png', null=True, upload_to='category/')),
                ('parant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='لا يوجد', null=True)),
                ('color_pro', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(limit_choices_to={'parant__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='lab.category')),
            ],
        ),
        migrations.CreateModel(
            name='image_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='product/notfound.png', upload_to='prodcut/')),
                ('main_image', models.BooleanField(default=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.product')),
            ],
        ),
    ]
