# Generated by Django 3.1.4 on 2022-10-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20221023_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='معروض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.category', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_pro',
            field=models.CharField(default=1, max_length=255, verbose_name='اللون'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='لا يوجد', null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='السعر'),
        ),
    ]
