# Generated by Django 3.1.4 on 2022-10-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20221023_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='category/notfound.png', upload_to='category/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.category', verbose_name='الصنف الأساسي إن وجد'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='Image',
            field=models.ImageField(default='product/notfound.png', upload_to='prodcut/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='أساسية'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.product', verbose_name='اسم المنتج'),
        ),
    ]
