# Generated by Django 3.1.4 on 2022-10-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20221024_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='media/category/notfound.png', upload_to='media/category/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='Image',
            field=models.ImageField(default='media/product/notfound.png', upload_to='media/prodcut/', verbose_name='الصورة'),
        ),
    ]
