# Generated by Django 3.1.4 on 2022-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20221026_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='Git_Baraa/lab-baraa/baraa/media/category/notfound.png', upload_to='Git_Baraa/lab-baraa/baraa/media/category/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='Image',
            field=models.ImageField(default='Git_Baraa/lab-baraa/baraa/media/product/notfound.png', upload_to='Git_Baraa/lab-baraa/baraa/media/prodcut/', verbose_name='الصورة'),
        ),
    ]
