# Generated by Django 4.1.6 on 2023-04-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_auto_20221027_1034"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parant",
            new_name="parent",
        ),
    ]
