# Generated by Django 4.1.6 on 2023-04-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_rename_parant_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="Image",
            field=models.ImageField(
                default="../media/category/notfound.png",
                upload_to="../media/category/",
                verbose_name="الصورة",
            ),
        ),
    ]
