# Generated by Django 4.1.6 on 2023-04-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0009_alter_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="Image",
            field=models.ImageField(
                default="../media/category/notfound.png",
                upload_to="media/category/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="image_product",
            name="Image",
            field=models.ImageField(
                default="../media/product/notfound.png",
                upload_to="media/prodcut/",
                verbose_name="الصورة",
            ),
        ),
    ]
