# Generated by Django 4.1.6 on 2023-04-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0012_alter_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_product",
            name="Image",
            field=models.ImageField(
                default="../media/prodcut/notfound.png",
                upload_to="media/prodcut/",
                verbose_name="الصورة",
            ),
        ),
    ]
